"""
Export Router — PDF report generation endpoint.
"""

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER
from services.data_service import get_dataframe, get_salary_df, get_skills, TARGET_ROLES
from collections import Counter

router = APIRouter()

PRIMARY = HexColor("#065A82")
ACCENT = HexColor("#02C39A")
GRAY = HexColor("#666666")
LIGHT_BG = HexColor("#F0F7FF")
LIGHT_GRAY = HexColor("#EEEEEE")


class ReportRequest(BaseModel):
    role: str
    region: str = "Global"
    user_name: str = ""


@router.post("/export-report")
def export_report(req: ReportRequest):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=2*cm, leftMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle("Title", parent=styles["Title"],
                                 fontSize=24, textColor=PRIMARY, spaceAfter=6, alignment=TA_CENTER)
    subtitle_style = ParagraphStyle("Sub", parent=styles["Normal"],
                                    fontSize=12, textColor=GRAY, spaceAfter=4, alignment=TA_CENTER)
    heading_style = ParagraphStyle("Head", parent=styles["Heading1"],
                                   fontSize=14, textColor=PRIMARY, spaceBefore=12, spaceAfter=6)
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                fontSize=10, textColor=black, spaceAfter=4, leading=14)

    # Header
    elements.append(Paragraph("🧠 CareerLens", title_style))
    elements.append(Paragraph("AI-Powered Job Market Intelligence Report", subtitle_style))
    elements.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
    elements.append(Spacer(1, 0.3*cm))
    elements.append(Paragraph(f"Role: <b>{req.role}</b> | Region: <b>{req.region}</b>", body_style))
    elements.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", body_style))
    if req.user_name:
        elements.append(Paragraph(f"Prepared for: <b>{req.user_name}</b>", body_style))
    elements.append(Spacer(1, 0.5*cm))

    # Market Overview
    df = get_dataframe()
    sal = get_salary_df(df)
    role_data = sal[sal["role_category"] == req.role]
    if req.region == "India":
        role_data = role_data[role_data["region"] == "India"]

    elements.append(Paragraph("1. Market Overview", heading_style))
    elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT_GRAY))

    if len(role_data) >= 5:
        p25 = role_data["salary_usd"].quantile(0.25)
        median = role_data["salary_usd"].median()
        p75 = role_data["salary_usd"].quantile(0.75)
        p90 = role_data["salary_usd"].quantile(0.90)

        total_jobs = len(df[df["role_category"] == req.role])
        overview_data = [
            ["Metric", "Value (USD)", "Value (INR)"],
            ["Total Job Postings", f"{total_jobs:,}", "-"],
            ["25th Percentile", f"${p25:,.0f}", f"₹{p25/1200:.1f} LPA"],
            ["Median Salary", f"${median:,.0f}", f"₹{median/1200:.1f} LPA"],
            ["75th Percentile", f"${p75:,.0f}", f"₹{p75/1200:.1f} LPA"],
            ["90th Percentile", f"${p90:,.0f}", f"₹{p90/1200:.1f} LPA"],
        ]
        table = Table(overview_data, colWidths=[6*cm, 5*cm, 5*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 1), (-1, -1), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, LIGHT_BG]),
            ("GRID", (0, 0), (-1, -1), 0.5, LIGHT_GRAY),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph(f"Insufficient salary data for {req.role}.", body_style))

    # Footer
    elements.append(Spacer(1, 1*cm))
    elements.append(HRFlowable(width="100%", thickness=1, color=LIGHT_GRAY))
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"],
                                  fontSize=8, textColor=GRAY, alignment=TA_CENTER)
    elements.append(Paragraph(f"Generated by CareerLens v2.0 | {datetime.now().strftime('%Y')}", footer_style))

    doc.build(elements)
    buffer.seek(0)

    filename = f"CareerLens_{req.role.replace('/', '_')}_{req.region}_{datetime.now().strftime('%Y%m%d')}.pdf"
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
